name: Database migration

permissions:
  contents: read

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

jobs:
  migration:
    runs-on: ubuntu-24.04
    environment: ${{ github.event_name == 'pull_request' && 'staging' || 'production' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: Perdolique/.github/.github/actions/setup-pnpm@master
        with:
          install-dependencies: true
      - name: Run database migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm run db:migrate
      - name: Seed database
        if: github.event_name == 'pull_request'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm run db:seed
